package view;

import controller.Controller;

public class AggiuntaGiocatori extends javax.swing.JFrame {
    
    private Controller controller;

    /**
     * Creates new form AggiuntaGiocatori
     * @param controller
     */
    public AggiuntaGiocatori(Controller controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new view.Sfondo2();
        pulsanteFatto = new javax.swing.JButton();
        pulsanteEsci = new javax.swing.JButton();
        areaTestoAggiungiGiocatori = new javax.swing.JTextField();
        pulsanteAggiungi = new javax.swing.JButton();
        etichettaAggiungiGiocatori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pulsanteFatto.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteFatto.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pulsanteFatto.setText("Fatto");
        pulsanteFatto.setBorderPainted(false);
        pulsanteFatto.setFocusPainted(false);
        pulsanteFatto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteFattoActionPerformed(evt);
            }
        });

        pulsanteEsci.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteEsci.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pulsanteEsci.setText("Esci");
        pulsanteEsci.setBorderPainted(false);
        pulsanteEsci.setFocusPainted(false);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        areaTestoAggiungiGiocatori.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        pulsanteAggiungi.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteAggiungi.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pulsanteAggiungi.setText("Aggiungi");
        pulsanteAggiungi.setBorderPainted(false);
        pulsanteAggiungi.setFocusPainted(false);
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });

        etichettaAggiungiGiocatori.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etichettaAggiungiGiocatori.setText("Aggiungi i nomi del giocatori");

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pulsanteEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pulsanteFatto)
                .addGap(100, 100, 100))
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(areaTestoAggiungiGiocatori, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteAggiungi))
                    .addComponent(etichettaAggiungiGiocatori))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(etichettaAggiungiGiocatori)
                .addGap(68, 68, 68)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaTestoAggiungiGiocatori, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulsanteAggiungi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsanteFatto)
                    .addComponent(pulsanteEsci))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteEsciActionPerformed
        System.exit(0);
    }//GEN-LAST:event_pulsanteEsciActionPerformed

    private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAggiungiActionPerformed
        String nome = areaTestoAggiungiGiocatori.getText();
        if (!nome.isEmpty())
        {
            if (controller.getGiocatori().size() != 10)
            {
                if (nome.length() <= 20)
                {
                    if (!controller.getGiocatori().contains(nome)) controller.addGiocatore(nome);
                    else new Errore("nome già presente").setVisible(true);
                }
                else new Errore("nome troppo lungo").setVisible(true);
            }
            else new Errore("massimo giocatori superato").setVisible(true);
            areaTestoAggiungiGiocatori.setText("");
        } else new Errore("nome non inserito").setVisible(true);
    }//GEN-LAST:event_pulsanteAggiungiActionPerformed

    private void pulsanteFattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteFattoActionPerformed
        if (controller.getGiocatori().size() > 1) {
            controller.startGioco();
            this.dispose();
        } else new Errore("inserire almeno 2 giocatori").setVisible(true);
    }//GEN-LAST:event_pulsanteFattoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaTestoAggiungiGiocatori;
    private javax.swing.JLabel etichettaAggiungiGiocatori;
    private javax.swing.JButton pulsanteAggiungi;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteFatto;
    private view.Sfondo2 sfondo;
    // End of variables declaration//GEN-END:variables
}
