package view;

import controller.Controller;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel
 */
public class CartaPescata extends javax.swing.JFrame {

    private FinestraGioco finestraGioco;
    private String cartaPescata;
    private int posizione;
    
    /**
     * Creates new form CartaPescata
     * @param finestraGioco
     * @param cartaPescata
     * @param compatibili
     * @param posizione
     */
    public CartaPescata(FinestraGioco finestraGioco, String cartaPescata, boolean compatibili, int posizione) {
        initComponents();
        this.finestraGioco = finestraGioco;
        this.cartaPescata = cartaPescata;
        this.posizione = posizione;
        jButton.setIcon(new ImageIcon(getClass().getResource("/immagini/" + cartaPescata + ".png")));
        if (!compatibili)
        {
            pulsanteScarta.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo21 = new view.Sfondo2();
        jButton = new javax.swing.JButton();
        etichettaCartaPescata = new javax.swing.JLabel();
        pulsanteScarta = new javax.swing.JButton();
        pulsanteOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        etichettaCartaPescata.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etichettaCartaPescata.setText("Carta pescata");

        pulsanteScarta.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteScarta.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pulsanteScarta.setText("Scarta");
        pulsanteScarta.setBorderPainted(false);
        pulsanteScarta.setFocusPainted(false);
        pulsanteScarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteScartaActionPerformed(evt);
            }
        });

        pulsanteOk.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteOk.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pulsanteOk.setText("Ok");
        pulsanteOk.setBorderPainted(false);
        pulsanteOk.setFocusPainted(false);
        pulsanteOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sfondo21Layout = new javax.swing.GroupLayout(sfondo21);
        sfondo21.setLayout(sfondo21Layout);
        sfondo21Layout.setHorizontalGroup(
            sfondo21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondo21Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(sfondo21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sfondo21Layout.createSequentialGroup()
                        .addComponent(etichettaCartaPescata)
                        .addGap(285, 285, 285))
                    .addGroup(sfondo21Layout.createSequentialGroup()
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(pulsanteScarta)
                        .addGap(18, 18, 18)
                        .addComponent(pulsanteOk)
                        .addGap(70, 70, 70))))
        );
        sfondo21Layout.setVerticalGroup(
            sfondo21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondo21Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(etichettaCartaPescata)
                .addGroup(sfondo21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondo21Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sfondo21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulsanteOk)
                            .addComponent(pulsanteScarta)))
                    .addGroup(sfondo21Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        
    }//GEN-LAST:event_jButtonActionPerformed

    private void pulsanteScartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteScartaActionPerformed
        finestraGioco.scartaCartaPescata(posizione);
        this.dispose();
    }//GEN-LAST:event_pulsanteScartaActionPerformed

    private void pulsanteOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteOkActionPerformed
        finestraGioco.stopPesca();
        this.dispose();
    }//GEN-LAST:event_pulsanteOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etichettaCartaPescata;
    private javax.swing.JButton jButton;
    private javax.swing.JButton pulsanteOk;
    private javax.swing.JButton pulsanteScarta;
    private view.Sfondo2 sfondo21;
    // End of variables declaration//GEN-END:variables
}
