package view;

import controller.Controller;
import java.util.ArrayList;

/**
 *
 * @author Gabriel
 */

public class Menu extends javax.swing.JFrame {
    
    private Controller controller;
    
    /**
     * Creates new form Menu
     * @param controller
     */
    public Menu(Controller controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new view.Sfondo1();
        etichettaTitolo = new javax.swing.JLabel();
        pulsanteGioca = new javax.swing.JButton();
        pulsanteEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        etichettaTitolo.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        etichettaTitolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_uno.png"))); // NOI18N

        pulsanteGioca.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteGioca.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pulsanteGioca.setText("Gioca");
        pulsanteGioca.setBorderPainted(false);
        pulsanteGioca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pulsanteGioca.setFocusPainted(false);
        pulsanteGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteGiocaActionPerformed(evt);
            }
        });

        pulsanteEsci.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteEsci.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pulsanteEsci.setText("Esci");
        pulsanteEsci.setBorderPainted(false);
        pulsanteEsci.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pulsanteEsci.setFocusPainted(false);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etichettaTitolo)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pulsanteGioca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(pulsanteEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(etichettaTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsanteEsci)
                    .addComponent(pulsanteGioca))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteEsciActionPerformed
        System.exit(0);
    }//GEN-LAST:event_pulsanteEsciActionPerformed

    private void pulsanteGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteGiocaActionPerformed
        new AggiuntaGiocatori(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pulsanteGiocaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etichettaTitolo;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteGioca;
    private view.Sfondo1 sfondo;
    // End of variables declaration//GEN-END:variables
}
