/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.SwingConstants;

/**
 *
 * @author Gabriel
 */
public class Vittoria extends javax.swing.JFrame {

    private Controller controller;
    private String giocatore;
    
    /**
     * Creates new form Vittoria
     * @param controller
     * @param giocatore
     */
    public Vittoria(Controller controller, String giocatore) {
        initComponents();
        etichettaVincitore.setText(giocatore);
        etichettaVincitore.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo11 = new view.Sfondo1();
        etichettaCongratulazioni = new javax.swing.JLabel();
        etichettaVincitore = new javax.swing.JLabel();
        pulsanteGiocaAncora = new javax.swing.JButton();
        pulsanteEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        etichettaCongratulazioni.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        etichettaCongratulazioni.setText("Congratulazioni!");

        etichettaVincitore.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etichettaVincitore.setText("wwwwwwwwwwwwwwwwwwwwwwwwwwwwww");

        pulsanteGiocaAncora.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteGiocaAncora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pulsanteGiocaAncora.setText("Gioca ancora");
        pulsanteGiocaAncora.setBorderPainted(false);
        pulsanteGiocaAncora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pulsanteGiocaAncora.setFocusPainted(false);
        pulsanteGiocaAncora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteGiocaAncoraActionPerformed(evt);
            }
        });

        pulsanteEsci.setBackground(new java.awt.Color(247, 227, 89));
        pulsanteEsci.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pulsanteEsci.setText("Esci");
        pulsanteEsci.setBorderPainted(false);
        pulsanteEsci.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pulsanteEsci.setFocusPainted(false);
        pulsanteEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sfondo11Layout = new javax.swing.GroupLayout(sfondo11);
        sfondo11.setLayout(sfondo11Layout);
        sfondo11Layout.setHorizontalGroup(
            sfondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondo11Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(pulsanteGiocaAncora)
                .addGap(18, 18, 18)
                .addComponent(pulsanteEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(etichettaVincitore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondo11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etichettaCongratulazioni)
                .addGap(124, 124, 124))
        );
        sfondo11Layout.setVerticalGroup(
            sfondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondo11Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(etichettaCongratulazioni)
                .addGap(18, 18, 18)
                .addComponent(etichettaVincitore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(sfondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsanteGiocaAncora)
                    .addComponent(pulsanteEsci))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteGiocaAncoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteGiocaAncoraActionPerformed
        this.dispose();
        controller = new Controller();
    }//GEN-LAST:event_pulsanteGiocaAncoraActionPerformed

    private void pulsanteEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteEsciActionPerformed
        System.exit(0);
    }//GEN-LAST:event_pulsanteEsciActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etichettaCongratulazioni;
    private javax.swing.JLabel etichettaVincitore;
    private javax.swing.JButton pulsanteEsci;
    private javax.swing.JButton pulsanteGiocaAncora;
    private view.Sfondo1 sfondo11;
    // End of variables declaration//GEN-END:variables
}
